### ISSUE TITLE
Android After Login it not return all info

### ISSUE THREAD

**Issue by mayurloved** [DrMoriarty/cordova-social-vk#11]
Hello,

Thanks for such plugin.

I have tried this plugin and working fine in iOS. But when i use same code in android for login then it only return userid,firstname,lastname and token. Its not returning user image.

Can you please help me..

Thanks in Advance

**Comment by DrMoriarty** [comment]
Hello!
Try this https://github.com/DrMoriarty/cordova-social-vk/commit/25d0efe5a48a60080c5ec3d4cd58af213f2c7944
is it worked as you expected?

**Comment by mayurloved** [comment]
Hi,

Thanks for Quick Replay.

Yeh I Tried this and it already works for me.!!

Thanks :)

**Comment by mayurloved** [comment]
Just for information in ios it return response in string where in ios it return object.
