### ISSUE TITLE
VKSdk.initialize

### ISSUE THREAD

**Issue by freebit** [DrMoriarty/cordova-social-vk#15]
Скажите пожалуйста, так в каком месте cordova приложения нужно вызывать `SocialVk.init`? Даже в "deviceready" лезет ошибка:

`VKSdk.initialize(Context) must be call from Application#onCreate()`

**Comment by DrMoriarty** [comment]
Вызывать надо как обычно, для всех плагинов. 
Вообще эта проверка в коде задокументирована
https://github.com/DrMoriarty/cordova-social-vk/blob/master/src/android/vksdk_library/src/com/vk/sdk/VKSdk.java

**Comment by freebit** [comment]
Получается у меня не та версия VKSdk?

**Comment by DrMoriarty** [comment]
в дебагере то можете посмотреть, откуда эксепшен кидается?

**Comment by freebit** [comment]
Эксепшена нет, ошибка приходит в errorCallback для `SocialVk.init`

**Comment by freebit** [comment]
А вообще нужен ли `SocialVk.init`, если мне нужно просто залогиниться?

**Comment by freebit** [comment]
Извините, не вдавался в подробности, хотел быстро прикрутить авторизацию через ВК для кородова-приложения

**Comment by freebit** [comment]
Добрый день. Можно я вас помучаю еще? Скажите, что нужно сделать еще после установки плагина в проект? Просто проект не билдится из за `error: package com.vk.sdk does not exist`. Я понимаю, что не хватает пакета, но так как опыта работы с java нет совсем, то и не знаю где его взять. Нашел вариант с Maven

```
dependencies { 
   compile 'com.vk:androidsdk:+' 
}
```

В таком виде проект вчера запустился, но выше я писал о проблеме, которая возникла.
Подскажите куда копать?

**Comment by DrMoriarty** [comment]
ну видимо отсюда и проблема растёт.

```
# cordova create vkplugintest
# cd vkplugintest
# cordova plugin add https://github.com/DrMoriarty/cordova-social-vk --variable VK_APP_ID=0000000
# cordova platform add android
# cordova build android

BUILD SUCCESSFUL

Total time: 44.075 secs
Built the following apk(s): 
    /Users/vasya/projects/Cordova/vkplugintest/platforms/android/build/outputs/apk/android-debug.apk

```

**Comment by freebit** [comment]
Вообщем у вас все работает на свежем проекте. Ваш листинг натолкнул на идею. Спасибо!

**Comment by freebit** [comment]
Для будущих поколений!
Сначала инсталим плагин, потом добавляем платформу.

**Comment by freebit** [comment]
Добрый день! На ios платформе, если не установлено нативное приложение от ВК, то плагин не открывает форму авторизации от ВК. Просто какое то время крутится прелоадер и все.

**Comment by DrMoriarty** [comment]
плагин установлен из npm или из github?

**Comment by freebit** [comment]
из гитхаба

**Comment by DrMoriarty** [comment]
С недавнего времени стабильная версия лежит в npm (см Readme)
а в гитхабе лежит нестабильная. Про описанную проблему я знаю. Ведутся работы.

**Comment by freebit** [comment]
в консоли сафари
`Can't find variable: VkSdk`

**Comment by freebit** [comment]
Оп, а clobbers то SocialVk

Секундочку...

**Comment by freebit** [comment]
Нет, проблема остается. Есть надежда на npm версию?

**Comment by DrMoriarty** [comment]
я сейчас обновляю sdk для этого плагина. Как только всё будет работать, так будет обновление в npm. Там сейчас залита старая рабочая версия (что не мешает ей иногда работать не корректно в связи с недавним обновлением VK API)

**Comment by freebit** [comment]
Ок, спасибо

**Comment by pro-m** [comment]
есть ли актуальная версия плагина?
На данный момент он ругается на несовместимую версию sdk (библиотеки вк)
