### ISSUE TITLE
Как получить токен через приложение?

### ISSUE THREAD

**Issue by jet174** [DrMoriarty/cordova-social-vk#19]
Добрый день, есть ли такая возможность получение токена через ваш плагин?
Пример как я использую:
function successVK(token){
    console.log(token+'success share');
}
function failVK(){
    console.log('fail share');
}
function loginVK(){
    console.log('sharing');
    window.SocialVk.login(['messages'], successVK(), failVK());
}
объясните пожалуйста как получить токен функция срабатывает до того как вылазиет авторизация?

**Comment by DrMoriarty** [comment]
Перед логином надо инициализировать плагин. Вот примерный код:

```
        SocialVk.init('123456789', function() {
            console.log('VK plugin', 'inited');
            SocialVk.login(['wall', 'offline', 'friends', 'audio', 'video', 'photos'], function(res) {                                                                 
                console.log('VK login', JSON.stringify(res));
            }, function(err) {
                // ERROR
            });
        }, function(err) {
            // ERROR
        });
```

Причём, вместо 123456789 надо поставить идентификатор вашего приложения ВК, тот же самый, который вы использовали при установке плагина.
