### ISSUE TITLE
How to use cordova-social-vk 

### ISSUE THREAD

**Issue by sempl84** [DrMoriarty/cordova-social-vk#2]
Firstly, thank you for your plugin for Cordova! Can you explain how to configure and use this plugin?

**Comment by DrMoriarty** [comment]
Hello!
Use this command
<code>
cordova plugin add https://github.com/DrMoriarty/cordova-social-vk.git  --variable VK_APP_ID='insert your VK app ID'
</code>

**Comment by arthemis91** [comment]
Здравствуйте, подскажите пожалуйста как нужно изменить настройки в plugin.xml андроид платформы для сборки в облаке Intel XDK. При текущих сборка проваливается так как  не удаётся добавить vksdk_library, а при изменении <source-file src="src/android/vksdk_library" ...> на   <framework src="src/android/vksdk_library" custom="true" />
сборка проходит успешно,но сам плагин перестаёт работать.

**Comment by DrMoriarty** [comment]
проблема сборки исправлена в https://github.com/DrMoriarty/cordova-social-vk/commit/197cd5033e13608e8e470d2932302d5c3e7de14d
