### ISSUE TITLE
IOS 9 после авторизации открывается inApp Browser

### ISSUE THREAD

**Issue by p3psic** [DrMoriarty/cordova-social-vk#23]
Здравствуйте!

В IOS9 при авторизации после разрешения пермишнов в приложении VK возвращает в наше приложение, но затем почему-то открывает inAppBrowser для повторной авторизации. Дип линкинг в приложении говорит о том, что при возвращении из приложения VK токен был получен. Мы пытались продебажить функцию логина в Вашем плагине, но дальше этого If'а продебажить почему-то не получилось.

> -(void) login:(CDVInvokedUrlCommand *)command
> {
>     NSArray *permissions = [command.arguments objectAtIndex:0];
>     if(![VKSdk isLoggedIn]) {

В чем может быть дело? Заранее спасибо.

**Comment by DrMoriarty** [comment]
этот if просто проверяет уже существующий логин (наличие токена внутри SDK), и если токен есть, тогда просто грузит данные по текущему пользователю.
Можете сформировать минимальное приложение для воспроизведения этой проблемы?

**Comment by p3psic** [comment]
Прошу прощения за долгий ответ. 

Согласен, но этот if работал странно. Внутри есть nslog и ни в одной ветке он не срабатывал. Вчера долго пытался поднять чистый проект ionic. Возникали ошибки arch (armv7 и i386) not found и error 65. После решения этих ошибок, все заработало и inAppBrowser не вызывался. 

Единственное но, это другой компьютер. Вот сейчас пытаюсь поднять этот же проект на рабочем компьютере и опять наткнулся на ошибку arch not found. 
Вы не знаете как она решается?
Вот ссылка на чистый проект https://drive.google.com/open?id=0B5JnYzj3kDskdFdhZ1pKTmxHRjg

**Comment by p3psic** [comment]
Проблема была с плагином ionic-plugin-deeplinks, который перехватывает все переходы из вне в мое приложение.
