### ISSUE TITLE
Can't add image to post when share

### ISSUE THREAD

**Issue by ivanvtimofeev** [DrMoriarty/cordova-social-vk#24]
Function SocialVk.share() works well but not add Image (third parameter) to the VK post

Фукнция SocialVk.share() работает нормально и отправляет пост на стену, но только не добавляет изображение. URL изображения передается третьим параметром. ОС iOS

**Comment by bayanistnahtc** [comment]
Здравствуйте! была ли решена проблема с добавлением картики?

**Comment by bayanistnahtc** [comment]
Решение удалось найти переставив местами аргументы: url картинки передавть первым
