### ISSUE TITLE
Как получить access_token для серверной авторизации?

### ISSUE THREAD

**Issue by artuska** [DrMoriarty/cordova-social-vk#32]
Сейчас получается так, что `token` и данные `user`, которые я получаю от SDK, абсолютно бесполезны — ими можно пользоваться только из самого SDK или из JavaScript SDK. А ведь мне нужен нормальный полный объект юзера с кучей данных — как если бы я авторизовывался через браузер. Тут я специально хочу облегчить задачу пользователю, лишь бы он не вводил логин/пароль (которые многие попросту не помнят) и для этого использую этот плагин и открываю нативную ВК-аппликацию — но ключи и данные, которые я получаю, с ними нельзя нормально работать, т.к. ключ, который я отсылаю на сервер, ВК потом не принимает и возвращает мне пустой `response`.

Почему-то `cordova-social-ok` и `cordova-plugin-facebook4` работают предсказуемо — я получаю токен от них и отдаю его на сервер, а на сервер бэкенд нормально получает данные от этих соц. сетей по токену, который я ему прислал.

Что мне нужно сделать, чтобы и ВК работал нормально?

**Comment by DrMoriarty** [comment]
доступ по токену с сервера в ВК делается совсем не так
https://vk.com/dev/access_token

**Comment by artuska** [comment]
@DrMoriarty тобишь, получается, что `cordova-social-vk` и вообще саму VK iOS SDK мне использовать бесполезно? Мне, таки, придётся открывать браузерский попап и юзеру придётся вводить логины/пароли, вместо того, чтобы открыть нативную ВК-аппликацию и без всяких вводов логинов/паролей авторизоваться и получить токен?

**Comment by artuska** [comment]
В общем, ясно, что токен от нативной аппликации и токен от браузерного логина это два разных токена и у них разные права. Это, конечно, ужасная архитектура, ибо токены от Фейсбука или Одноклассников я без проблем могу использовать на сервере, не меняя авторизационный флоу — как в браузере я получаю токен и шлю его на бэкенд, так и от аппликаций ФБ и ОК я получаю токен и передаю его на бэкенд... и всё отлично, но у ВК какое-то своё видение, максимально несоответствующее всем остальным социальным сервисам, по типу «а давайте максимально осложним жизнь для разработчиков и пусть для ВК они придумывают костыли»...
