### ISSUE TITLE
Ошибка сборки для android 4.2.2 (API 17)

### ISSUE THREAD

**Issue by nerevar** [DrMoriarty/cordova-social-vk#6]
Здравствуйте.

Сталкиваюсь с ошибкой сборки проекта ionic-cordova с подключённым `cordova-social-vk`: http://pastebin.com/n7TD1nwC

Подскажите пожалуйста, как сейчас правильно подключить плагин и собрать проект?

Я предположил, что дело в ссылке на `vksdk_library` и начал копать в эту сторону, подключать эту либо во всевозможные файлы, но это мне не помогло:

В тикете https://github.com/DrMoriarty/cordova-social-vk/issues/2 прилинкован коммит https://github.com/DrMoriarty/cordova-social-vk/commit/197cd5033e13608e8e470d2932302d5c3e7de14d с добавлением строки `android.library.reference.2=vksdk_library` в конфиг, но сейчас в ветке `master` этого кода нет.
Сейчас в конфиге всего проекта `platforms/android/project.properties` автоматически прописывается: `android.library.reference.3=ru.trilan.cordova-social-vk/photoquest634976-vksdk_library`

**Comment by DrMoriarty** [comment]
Оно не может скомпилировать vksdk, чтобы понять что именно сломалось нужно сделать как советуют в логе
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Подробный лог сюда приложите, я сам с ionicом пока не работал.

**Comment by nerevar** [comment]
Разобрался в чём было [дело](http://stackoverflow.com/questions/25805025/appcompiledebugjava-failed-at-android-studio-ide).
Из лога сборки:

> JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
> ...
> invalid source release: 1.7

У меня был установлен старый JDK 1.6.
Установил 1.7, [прописал](http://stackoverflow.com/questions/6588390/where-is-java-home-on-osx-yosemite-10-10-mavericks-10-9-mountain-lion-10) правильный  `JAVA_HOME` и всё заработало.

Такие дела :)
