### ISSUE TITLE
users_search и wall_post не работают с параметрами

### ISSUE THREAD

**Issue by RomaRogov** [DrMoriarty/cordova-social-vk#7]
Например, когда я передаю в wall_post информацию в виде объекта, то он просто постит на стене этот объект в виде JSON строки.

Полагаю, `optString(0)` возвращает строку с JSONом параметров, а не null, а проверка производится сначала на переменную, которая содержит в себе результат `optString(0)`, и только потом на переменную, содержащую `optJSONObject(0)`.

Если поменять последовательность проверки (сначала `if(params != null)`, а потом `if(message != null)`, то постинг работает как надо.

**Comment by DrMoriarty** [comment]
fixed by https://github.com/DrMoriarty/cordova-social-vk/commit/cf0f8013f400d85cae3ed7d2a89412d2de255032
