### ISSUE TITLE
Проблема под iOS

### ISSUE THREAD

**Issue by DMerva** [DrMoriarty/cordova-social-vk#9]
Здравствуйте.
После установки плагина, проект перестал компилироваться в Xcode5
Ошибка:
Project/Plugins/ru.trilan.cordova-social-vk/SocialVk.h:5:9: 'VKSdk/VKSdk.h' file not found

Скажите, нужны еще какие-то манипуляции в Xcode после установки?
Спасибо.

**Comment by DrMoriarty** [comment]
Там иногда кордова глючит и забывает добавит фреймворк в проект.
Надо тогда вручную включить VKSdk.framework

**Comment by DMerva** [comment]
Фреймворк VKSdk.framework у меня вроде добавлен, на закладке Build Phases в разделе Link Binnary with Libraries он есть. Но чего-то не находит VKSdk.h и я не очень разбираюсь в этом XCode.

**Comment by DrMoriarty** [comment]
могу предложить простой вариант
создать нулёвый тестовый проект и добавить в него этот плагин
если проект потом соберётся - искать у себя разницу
если не соберётся, то зазиповать и сюда ссылку прислать

**Comment by DMerva** [comment]
Разобрался в чем проблема, Вы использовали ссылки внутри VKSdk.framework:
Headers -> Versions/Current/Headers
VKSdk -> Versions/Current/VKSdk
а я работаю под Windows и у меня при установке плагина ссылки превратились в текстовые файлики. Лучше сделать без ссылок они там как я понимаю не нужны.
А вообще отличная работа, спасибо!

**Comment by artuska** [comment]
Тоже была такая проблема. Фреймворк лежит вот по такому пути:

```
/cordova/platforms/ios/{название_проекта}/Plugins/cordova-social-vk/VKSdk.framework
```
и дальше там была папка `Version`, в ней была папка `А` и уже там были ресурсы `Headers` и `VKSdk` — так вот я их просто перетянул в `VKSdk.framework`, а саму папку `Version` удалил.
